version: '3.9'
services:
    migration:
        container_name: moviesapis_django_migration
        image: nurhun/django_rest_framework_movies_apis_w_react_frontend_backend:v0.1.0
        # build:
        #     context: ./
        #     dockerfile: ./docker/backend/Dockerfile
        command:  ["-c" , "python manage.py makemigrations && python manage.py migrate || true"]

    backend:
        container_name: moviesapis_django_rest
        restart: always
        image: nurhun/django_rest_framework_movies_apis_w_react_frontend_backend:v0.1.0
        # build:
        #     context: ./
        #     dockerfile: ./docker/backend/Dockerfile
        command: 
        - "-c"
        - |
            python manage.py collectstatic --noinput
            gunicorn moviesapi.wsgi --bind=0.0.0.0:8000 --reload --workers=2 --threads=2 --timeout=120 --log-level=warning
        ports:
            - 8000:8000
        depends_on:
            migration:
                condition: service_completed_successfully
        healthcheck:
            test: ["CMD-SHELL", "curl -f -XGET -H 'Accept: application/json' http://backend:8000/ht/"]
            interval: 1s
            timeout: 5s
            retries: 5
            start_period: 3s

    nginx:
        container_name: moviesapis_frontend_nginx
        restart: always
        image: nurhun/django_rest_framework_movies_apis_w_react_frontend_nginx:v0.1.0
        # build:
        #     context: ./
        #     dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            backend:
                condition: service_healthy
