# Generated by Django 4.1.3 on 2022-12-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='story_line',
        ),
    ]
